# This is a full example of how to run the oauth2 example. Using this example requires you to
# have WADM running: https://github.com/wasmCloud/wadm/tree/main/wadm and a host labeled with
# `app=oauth2`. You can deploy this example with two simple commands:
#
# `wash app put wadm.yaml`
# `wash app deploy oauth2 0.0.1`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: oauth2
  annotations:
    version: v0.0.1
    description: "Jammin Oauth2 Sample"
spec:
  components:
    - name: oauth2_pkce
      type: actor
      properties:
        image: ghcr.io/jamminmusic/features/oauth2/oauth2_actors/oauth2_pkce:dev
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: oauth2_pkce
                requirements:
                  app: oauth2
        - type: linkdef
          properties:
            target: messaging_provider
            values:
              SUBSCRIPTION: "oauth2.login.*"
        - type: linkdef
          properties:
            target: httpclient_provider
            values:
              port: "8080"
        - type: linkdef
          properties:
            target: vault_provider
            values:
              token: "00000000-0000-0000-0000-000000000000"
        - type: linkdef
          properties:
            target: redis_provider
            values:
              URL: "redis://127.0.0.1:6379"

    - name: apigw_router
      type: actor
      properties:
        image: ghcr.io/jamminmusic/features/apigw/apigw_actors/apigw_router:dev
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: apigw_router
                requirements:
                  app: oauth2
        - type: linkdef
          properties:
            target: httpserver_provider
            values:
              port: "8080"

    ##################################################
    ## PLACEHOLDER TO TRY TO DEPLOY DIOXUS WITH WADM
    # - name: pwa
    #   type: actor - SHOULD THERE BE ANOTHER TPYE?
    ###################################################

    - name: messaging_provider
      type: capability
      properties:
        image: wasmcloud.azurecr.io/nats_messaging:0.15.0
        contract: wasmcloud:messaging
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: messaging_provider_spread
                requirements:
                  app: oauth2

    - name: httpclient_provider
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpclient:0.6.0
        contract: wasmcloud:httpclient
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: httpclient_spread
                requirements:
                  app: oauth2

    - name: httpserver_provider
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.16.0
        contract: wasmcloud:httpserver
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: httpserver_spread
                requirements:
                  app: oauth2

    - name: vault_provider
      type: capability
      properties:
        image: wasmcloud.azurecr.io/kv-vault:0.2.3
        contract: wasmcloud:keyvalue
        link_name: vault
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: vault_spread
                requirements:
                  app: oauth2

    - name: redis_provider
      type: capability
      properties:
        image: wasmcloud.azurecr.io/kvredis:0.16.3
        contract: wasmcloud:keyvalue
        link_name: redis
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: redis_spread
                requirements:
                  app: oauth2
